# Data Preprocessing

* Imporing python library
* Reading Data
* Missing Data
* Deal with Categorical data
* Splitting data
* Normlize data

### Import Python Library, Read Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("Data.csv")

In [3]:
data

City   Age Smoke  HappinessIndex Healthy
0   Mumbai  24.0   Yes           241.0     Yes
1   London  80.0    No           928.0      No
2  NewYork  38.0   Yes             NaN     Yes
3  NewYork  22.0   Yes           786.0     Yes
4  NewYork  36.0   Yes           967.0     Yes
5   London   NaN   Yes           665.0     Yes
6   Mumbai  17.0    No           293.0      No
7  NewYork  28.0    No           494.0     Yes
8   Mumbai  45.0    No           707.0      No
9   London  29.0   Yes           599.0      No

In [4]:
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values

In [5]:
X

array([['Mumbai', 24.0, 'Yes', 241.0],
       ['London', 80.0, 'No', 928.0],
       ['NewYork', 38.0, 'Yes', nan],
       ['NewYork', 22.0, 'Yes', 786.0],
       ['NewYork', 36.0, 'Yes', 967.0],
       ['London', nan, 'Yes', 665.0],
       ['Mumbai', 17.0, 'No', 293.0],
       ['NewYork', 28.0, 'No', 494.0],
       ['Mumbai', 45.0, 'No', 707.0],
       ['London', 29.0, 'Yes', 599.0]], dtype=object)

In [6]:
y

array(['Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'], dtype=object)

# Missing Data

In [7]:
X

array([['Mumbai', 24.0, 'Yes', 241.0],
       ['London', 80.0, 'No', 928.0],
       ['NewYork', 38.0, 'Yes', nan],
       ['NewYork', 22.0, 'Yes', 786.0],
       ['NewYork', 36.0, 'Yes', 967.0],
       ['London', nan, 'Yes', 665.0],
       ['Mumbai', 17.0, 'No', 293.0],
       ['NewYork', 28.0, 'No', 494.0],
       ['Mumbai', 45.0, 'No', 707.0],
       ['London', 29.0, 'Yes', 599.0]], dtype=object)

In [8]:
from sklearn.preprocessing import Imputer

In [9]:
imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)

In [10]:
X[:,1:2] = imputer.fit_transform(X[:,1:2])   # fit + transform = fit_transform
X[:,3:4] = imputer.fit_transform(X[:,3:4]) 

In [11]:
(24 + 80 + 38 + 22 + 36 + 17 + 28 + 45 + 29) / 9

35.44444444444444

In [12]:
X

array([['Mumbai', 24.0, 'Yes', 241.0],
       ['London', 80.0, 'No', 928.0],
       ['NewYork', 38.0, 'Yes', 631.1111111111111],
       ['NewYork', 22.0, 'Yes', 786.0],
       ['NewYork', 36.0, 'Yes', 967.0],
       ['London', 35.44444444444444, 'Yes', 665.0],
       ['Mumbai', 17.0, 'No', 293.0],
       ['NewYork', 28.0, 'No', 494.0],
       ['Mumbai', 45.0, 'No', 707.0],
       ['London', 29.0, 'Yes', 599.0]], dtype=object)

# Categorical Data

In [13]:
X

array([['Mumbai', 24.0, 'Yes', 241.0],
       ['London', 80.0, 'No', 928.0],
       ['NewYork', 38.0, 'Yes', 631.1111111111111],
       ['NewYork', 22.0, 'Yes', 786.0],
       ['NewYork', 36.0, 'Yes', 967.0],
       ['London', 35.44444444444444, 'Yes', 665.0],
       ['Mumbai', 17.0, 'No', 293.0],
       ['NewYork', 28.0, 'No', 494.0],
       ['Mumbai', 45.0, 'No', 707.0],
       ['London', 29.0, 'Yes', 599.0]], dtype=object)

In [14]:
y

array(['Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No'], dtype=object)

In [15]:
 Yes -> 1 , No -> 0 - LabelEncoder
 M -> 0, L -> 1,  N -> 2
Mumbai London Newyork
  1      0       0    -> One Hot Encoder
  0      1       0

SyntaxError: invalid syntax (<ipython-input-15-bc2629cf31df>, line 1)

In [16]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [17]:
le_x = LabelEncoder()
le_y = LabelEncoder()

In [18]:
X[:, 0] = le_x.fit_transform(X[:, 0])
X[:, 2] = le_x.fit_transform(X[:, 2])
y = le_y.fit_transform(y)

In [19]:
X

array([[1, 24.0, 1, 241.0],
       [0, 80.0, 0, 928.0],
       [2, 38.0, 1, 631.1111111111111],
       [2, 22.0, 1, 786.0],
       [2, 36.0, 1, 967.0],
       [0, 35.44444444444444, 1, 665.0],
       [1, 17.0, 0, 293.0],
       [2, 28.0, 0, 494.0],
       [1, 45.0, 0, 707.0],
       [0, 29.0, 1, 599.0]], dtype=object)

In [20]:
y

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 0], dtype=int64)

In [21]:
ohe = OneHotEncoder(categorical_features=[0])

In [22]:
X = ohe.fit_transform(X).toarray()

In [ ]:
X

# Spiliting data in Train and Test

In [24]:
# Machine Learning  = Training + Testing

In [41]:
from sklearn.cross_validation import train_test_split

In [42]:
X_train ,X_test, y_train, y_test  = train_test_split(X, y, test_size=0.3)

In [43]:
X

array([[   0.        ,    1.        ,    0.        ,   24.        ,
           1.        ,  241.        ],
       [   1.        ,    0.        ,    0.        ,   80.        ,
           0.        ,  928.        ],
       [   0.        ,    0.        ,    1.        ,   38.        ,
           1.        ,  631.11111111],
       [   0.        ,    0.        ,    1.        ,   22.        ,
           1.        ,  786.        ],
       [   0.        ,    0.        ,    1.        ,   36.        ,
           1.        ,  967.        ],
       [   1.        ,    0.        ,    0.        ,   35.44444444,
           1.        ,  665.        ],
       [   0.        ,    1.        ,    0.        ,   17.        ,
           0.        ,  293.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
           0.        ,  494.        ],
       [   0.        ,    1.        ,    0.        ,   45.        ,
           0.        ,  707.        ],
       [   1.        ,    0.        ,

In [28]:
X_train

array([[   1.        ,    0.        ,    0.        ,   35.44444444,
           1.        ,  665.        ],
       [   0.        ,    1.        ,    0.        ,   45.        ,
           0.        ,  707.        ],
       [   0.        ,    1.        ,    0.        ,   24.        ,
           1.        ,  241.        ],
       [   0.        ,    0.        ,    1.        ,   38.        ,
           1.        ,  631.11111111],
       [   1.        ,    0.        ,    0.        ,   29.        ,
           1.        ,  599.        ],
       [   0.        ,    0.        ,    1.        ,   36.        ,
           1.        ,  967.        ],
       [   1.        ,    0.        ,    0.        ,   80.        ,
           0.        ,  928.        ]])

In [29]:
y_train

array([1, 0, 1, 1, 0, 1, 0], dtype=int64)

In [30]:
X_test

array([[   0.,    0.,    1.,   28.,    0.,  494.],
       [   0.,    1.,    0.,   17.,    0.,  293.],
       [   0.,    0.,    1.,   22.,    1.,  786.]])

In [31]:
y_test

array([1, 0, 1], dtype=int64)

# Normalize data

In [32]:
X_train

array([[   1.        ,    0.        ,    0.        ,   35.44444444,
           1.        ,  665.        ],
       [   0.        ,    1.        ,    0.        ,   45.        ,
           0.        ,  707.        ],
       [   0.        ,    1.        ,    0.        ,   24.        ,
           1.        ,  241.        ],
       [   0.        ,    0.        ,    1.        ,   38.        ,
           1.        ,  631.11111111],
       [   1.        ,    0.        ,    0.        ,   29.        ,
           1.        ,  599.        ],
       [   0.        ,    0.        ,    1.        ,   36.        ,
           1.        ,  967.        ],
       [   1.        ,    0.        ,    0.        ,   80.        ,
           0.        ,  928.        ]])

In [ ]:
35.44444444,
665

In [ ]:
 45.        ,
707.        ]

In [ ]:
sqrt((X2-x1)^2 + (Y2-y1)^2)  = sqrt(1 + 100 + 1600) = sqrt(1700)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sc_x = StandardScaler()

In [ ]:
(X - Xmin)/ (Range = max - min)  ->  (X - Xmean) / XStd

In [44]:
X_test

array([[   0.,    1.,    0.,   24.,    1.,  241.],
       [   1.,    0.,    0.,   80.,    0.,  928.],
       [   0.,    0.,    1.,   28.,    0.,  494.]])

In [48]:
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [49]:
X_train

array([[ 1.58113883, -0.63245553, -0.8660254 , -0.3087731 ,  0.63245553,
        -0.34301055],
       [-0.63245553,  1.58113883, -0.8660254 , -1.64267291, -1.58113883,
        -1.95740442],
       [ 1.58113883, -0.63245553, -0.8660254 ,  0.4075805 ,  0.63245553,
         0.00519205],
       [-0.63245553,  1.58113883, -0.8660254 ,  1.46975998, -1.58113883,
         0.22677553],
       [-0.63245553, -0.63245553,  1.15470054, -1.08688133,  0.63245553,
         0.64356349],
       [-0.63245553, -0.63245553,  1.15470054,  0.46933512,  0.63245553,
         1.59848274],
       [-0.63245553, -0.63245553,  1.15470054,  0.69165175,  0.63245553,
        -0.17359884]])

In [50]:
X_test

array([[-0.63245553,  1.58113883, -0.8660254 , -0.86456469,  0.63245553,
        -2.23174586],
       [ 1.58113883, -0.63245553, -0.8660254 ,  5.36030109, -1.58113883,
         1.39272666],
       [-0.63245553, -0.63245553,  1.15470054, -0.41993142, -1.58113883,
        -0.89696923]])

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("titanic.csv")

In [3]:
data

No Class     Sex    Age Survived Freq
0    1   1st    Male  Child       No    0
1    2   2nd    Male  Child       No    0
2    3   3rd    Male  Child       No   35
3    4  Crew    Male  Child       No    0
4    5   1st  Female  Child       No    0
5    6   2nd  Female  Child       No   0␊
6    7   3rd  Female  Child       No   17
7    8  Crew  Female  Child       No    0
8    9   1st    Male  Adult       No  118
9   10   2nd    Male  Adult       No  154
10  11   3rd    Male  Adult       No  387
11  12  Crew    Male  Adult       No  670
12  13   1st  Female  Adult       No    4
13  14   2nd  Female  Adult       No   13
14  15   3rd  Female  Adult       No   89
15  16  Crew  Female  Adult       No    3
16  17   1st    Male  Child      Yes    5
17  18   2nd    Male  Child      Yes   11
18  19   3rd    Male  Child      Yes   13
19  20  Crew    Male  Child      Yes    0
20  21   1st  Female  Child      Yes    1
21  22   2nd  Female  Child      Yes   13
22  23   3rd  Female  Child      Yes   14
23  24  Crew  Female  Child      Yes    0
24  25   1st    Male  Adult      Yes   57
25  26   2nd    Male  Adult      Yes   14
26  27   3rd    Male  Adult      Yes   75
27  28  Crew    Male  Adult      Yes  192
28  29   1st  Female  Adult      Yes  140
29  30   2nd  Female  Adult      Yes   80