# Numpy

* Numeric Python
* One of Core Library for scientific computing in python
* Many advantage over python list
* High performace 1-D vector and 2-D Matrices processing
* Linear algebra operation
* Many of python scientific computing library use numpy as backand - SciKit Learn



# Topics

* Numpy array
* Array operataions
* Array Indexing and Slicing

# Installtion :
    
    conda install numpy
    pip install numpy

In [2]:
import numpy as np

# Numpy Array

In [ ]:
1D List -> Numpy array
2D Matrix -> Numpy array

In [3]:
vec = [1, 2, 3]

In [4]:
np_vec = np.array(vec)

In [5]:
np_vec

array([1, 2, 3])

In [6]:
type(np_vec)

numpy.ndarray

In [24]:
mat = [[2,6,8],[3,7,0],[2,6,8],[3,7,0]]

In [25]:
np_mat = np.array(mat)

In [26]:
np_mat

array([[2, 6, 8],
       [3, 7, 0],
       [2, 6, 8],
       [3, 7, 0]])

# Zeros, Ones, Eye

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [30]:
np.diag(np_mat,k= -1 )

array([3, 6, 0])

# Random

In [20]:
np.random.randn(5)

array([-1.41815355, -0.04928304,  1.12812606, -0.42331519, -0.33591286])

In [21]:
np.random.randn(3,4)

array([[-0.60737981, -1.61462413,  0.95042819,  0.28594445],
       [-0.98910804, -1.22823542,  0.40494029,  0.15097494],
       [ 0.75689391,  0.81611637,  1.00869387, -0.26302807]])

In [24]:
np.random.randint(5,150,5)

array([ 32, 125, 131,  63,  10])

# arange, linspace

In [26]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

In [29]:
np.linspace(2,5,10)

array([ 2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ])

In [30]:
np_vec

array([1, 2, 3])

In [31]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [33]:
np_mat.shape

(2, 3)

In [35]:
np_vec.min()

1

In [40]:
np_mat

array([[2, 6, 8],
       [3, 7, 0]])

In [44]:
np_mat.reshape(1,6)

array([[2, 6, 8, 3, 7, 0]])

In [45]:
np_mat.dtype

dtype('int32')

# Numpy Array Operation

In [61]:
a = np.array([0,1,2,3,4,5])

In [62]:
a + 7

array([ 7,  8,  9, 10, 11, 12])

In [63]:
a - 2

array([-2, -1,  0,  1,  2,  3])

In [64]:
a * 3

array([ 0,  3,  6,  9, 12, 15])

In [65]:
a / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5])

In [67]:
a

array([0, 1, 2, 3, 4, 5])

In [69]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [70]:
np.sum(a)

15

In [71]:
np.mean(a)

2.5

In [73]:
a1 = np.array([[1,3],[4,6]])
b1 = np.array([[0,2],[3,1]])

In [74]:
a1

array([[1, 3],
       [4, 6]])

In [75]:
b1

array([[0, 2],
       [3, 1]])

In [76]:
a1 + b1

array([[1, 5],
       [7, 7]])

In [77]:
a1 - b1

array([[1, 1],
       [1, 5]])

In [78]:
a1 * b1

array([[ 0,  6],
       [12,  6]])

In [79]:
a1.dot(b1)  # --> dot  here refers to matrix maultiplication

array([[ 9,  5],
       [18, 14]])

In [80]:
a

array([0, 1, 2, 3, 4, 5])

In [81]:
a > 2

array([False, False, False,  True,  True,  True], dtype=bool)

# Indexing, Slicing , Broadcasting

In [82]:
d1 = np.arange(25)

In [83]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [84]:
d2 = np.arange(25).reshape(5,5)

In [85]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
d1[4:12]  #d1[start: end+1]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
d1[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24])

In [88]:
d1[:13]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [89]:
d2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [91]:
d2[2,1]  #d2[row,column]

11

In [93]:
d2[:,3]

array([ 3,  8, 13, 18, 23])

In [94]:
d2[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [95]:
d1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [97]:
d1[0:5] = -10

In [98]:
d1

array([-10, -10, -10, -10, -10,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])